name: CI/CD for Telegram Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/water-reminder-bot:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/water-reminder-bot:latest

    - name: Run bot in container
      run: |
        docker run -d \
          -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          --name water-bot \
          ${{ secrets.DOCKER_USERNAME }}/water-reminder-bot:latest
